;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Attributes.Item.AttachableSurface",NewTagName="Properties.Item.AttachableSurface")
+GameplayTagRedirects=(OldTagName="Attributes.Item.Grabbable",NewTagName="Properties.Item.Grabbable")
+GameplayTagRedirects=(OldTagName="Attributes.Item.Stowable",NewTagName="Properties.Item.Stowable")
+GameplayTagRedirects=(OldTagName="Attributes.Item.Throwable",NewTagName="Properties.Item.Throwable")
+GameplayTagRedirects=(OldTagName="Attributes.Item",NewTagName="Properties.Item")
+GameplayTagRedirects=(OldTagName="Attributes",NewTagName="Properties")
+GameplayTagList=(Tag="Ability.Item.Activate",DevComment="")
+GameplayTagList=(Tag="Ability.Item.Activate.Coolant",DevComment="")
+GameplayTagList=(Tag="Attribute",DevComment="")
+GameplayTagList=(Tag="Attribute.Item.Ablation",DevComment="")
+GameplayTagList=(Tag="Attribute.Item.Heat",DevComment="")
+GameplayTagList=(Tag="Attribute.Item.Mass",DevComment="")
+GameplayTagList=(Tag="Attribute.Item.Stability",DevComment="")
+GameplayTagList=(Tag="Data.Magnitude",DevComment="")
+GameplayTagList=(Tag="Properties.Item.AttachableSurface",DevComment="")
+GameplayTagList=(Tag="Properties.Item.Grabbable",DevComment="")
+GameplayTagList=(Tag="Properties.Item.Stowable",DevComment="")
+GameplayTagList=(Tag="Properties.Item.Throwable",DevComment="")
+GameplayTagList=(Tag="Status.Heat.Burning",DevComment="")
+GameplayTagList=(Tag="Status.Heat.Explosive",DevComment="")
+GameplayTagList=(Tag="Status.Heat.Optimal",DevComment="")
+GameplayTagList=(Tag="Status.Heat.Overheating",DevComment="")
+GameplayTagList=(Tag="Type.Item.Activated",DevComment="")
+GameplayTagList=(Tag="Type.Item.BoltOn",DevComment="")
+GameplayTagList=(Tag="Type.Item.Catalyst",DevComment="")
+GameplayTagList=(Tag="Type.Item.Engine",DevComment="")
+GameplayTagList=(Tag="Type.Item.Fuel",DevComment="")
+GameplayTagList=(Tag="Type.Item.Thruster",DevComment="")
+GameplayTagList=(Tag="Type.Item.Wall",DevComment="")
+GameplayTagList=(Tag="Type.Ship.Segment",DevComment="")
+GameplayTagList=(Tag="Type.Ship.Segment.Body",DevComment="")
+GameplayTagList=(Tag="Type.Ship.Segment.Nose",DevComment="")
+GameplayTagList=(Tag="Type.Ship.Segment.Tail",DevComment="")
+GameplayTagList=(Tag="Status.Adhered",DevComment="")

