;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attributes.Item.AttachableSurface",DevComment="")
+GameplayTagList=(Tag="Attributes.Item.Grabbable",DevComment="")
+GameplayTagList=(Tag="Attributes.Item.Stowable",DevComment="")
+GameplayTagList=(Tag="Attributes.Item.Throwable",DevComment="")
+GameplayTagList=(Tag="Data.Magnitude",DevComment="")
+GameplayTagList=(Tag="Status.Heat.Burning",DevComment="")
+GameplayTagList=(Tag="Status.Heat.Explosive",DevComment="")
+GameplayTagList=(Tag="Status.Heat.Optimal",DevComment="")
+GameplayTagList=(Tag="Status.Heat.Overheating",DevComment="")

